#include <stddef.h>
#include "hostkey_sdl.h"

typedef struct {
    SDL_Scancode scancode;
    HOST_KEY_SCANCODE_t host_scan;
} HOSTKEY_SDL_MAP_t;

static const HOSTKEY_SDL_MAP_t hostkey_sdl_map[] = {
    { SDL_SCANCODE_ESCAPE, HOST_KEY_SCAN_ESCAPE },
    { SDL_SCANCODE_1, HOST_KEY_SCAN_1 },
    { SDL_SCANCODE_2, HOST_KEY_SCAN_2 },
    { SDL_SCANCODE_3, HOST_KEY_SCAN_3 },
    { SDL_SCANCODE_4, HOST_KEY_SCAN_4 },
    { SDL_SCANCODE_5, HOST_KEY_SCAN_5 },
    { SDL_SCANCODE_6, HOST_KEY_SCAN_6 },
    { SDL_SCANCODE_7, HOST_KEY_SCAN_7 },
    { SDL_SCANCODE_8, HOST_KEY_SCAN_8 },
    { SDL_SCANCODE_9, HOST_KEY_SCAN_9 },
    { SDL_SCANCODE_0, HOST_KEY_SCAN_0 },
    { SDL_SCANCODE_MINUS, HOST_KEY_SCAN_MINUS },
    { SDL_SCANCODE_EQUALS, HOST_KEY_SCAN_EQUALS },
    { SDL_SCANCODE_BACKSPACE, HOST_KEY_SCAN_BACKSPACE },
    { SDL_SCANCODE_TAB, HOST_KEY_SCAN_TAB },
    { SDL_SCANCODE_Q, HOST_KEY_SCAN_Q },
    { SDL_SCANCODE_W, HOST_KEY_SCAN_W },
    { SDL_SCANCODE_E, HOST_KEY_SCAN_E },
    { SDL_SCANCODE_R, HOST_KEY_SCAN_R },
    { SDL_SCANCODE_T, HOST_KEY_SCAN_T },
    { SDL_SCANCODE_Y, HOST_KEY_SCAN_Y },
    { SDL_SCANCODE_U, HOST_KEY_SCAN_U },
    { SDL_SCANCODE_I, HOST_KEY_SCAN_I },
    { SDL_SCANCODE_O, HOST_KEY_SCAN_O },
    { SDL_SCANCODE_P, HOST_KEY_SCAN_P },
    { SDL_SCANCODE_LEFTBRACKET, HOST_KEY_SCAN_LEFTBRACKET },
    { SDL_SCANCODE_RIGHTBRACKET, HOST_KEY_SCAN_RIGHTBRACKET },
    { SDL_SCANCODE_RETURN, HOST_KEY_SCAN_ENTER },
    { SDL_SCANCODE_LCTRL, HOST_KEY_SCAN_LEFTCTRL },
    { SDL_SCANCODE_A, HOST_KEY_SCAN_A },
    { SDL_SCANCODE_S, HOST_KEY_SCAN_S },
    { SDL_SCANCODE_D, HOST_KEY_SCAN_D },
    { SDL_SCANCODE_F, HOST_KEY_SCAN_F },
    { SDL_SCANCODE_G, HOST_KEY_SCAN_G },
    { SDL_SCANCODE_H, HOST_KEY_SCAN_H },
    { SDL_SCANCODE_J, HOST_KEY_SCAN_J },
    { SDL_SCANCODE_K, HOST_KEY_SCAN_K },
    { SDL_SCANCODE_L, HOST_KEY_SCAN_L },
    { SDL_SCANCODE_SEMICOLON, HOST_KEY_SCAN_SEMICOLON },
    { SDL_SCANCODE_APOSTROPHE, HOST_KEY_SCAN_APOSTROPHE },
    { SDL_SCANCODE_GRAVE, HOST_KEY_SCAN_GRAVE },
    { SDL_SCANCODE_LSHIFT, HOST_KEY_SCAN_LEFTSHIFT },
    { SDL_SCANCODE_BACKSLASH, HOST_KEY_SCAN_BACKSLASH },
    { SDL_SCANCODE_Z, HOST_KEY_SCAN_Z },
    { SDL_SCANCODE_X, HOST_KEY_SCAN_X },
    { SDL_SCANCODE_C, HOST_KEY_SCAN_C },
    { SDL_SCANCODE_V, HOST_KEY_SCAN_V },
    { SDL_SCANCODE_B, HOST_KEY_SCAN_B },
    { SDL_SCANCODE_N, HOST_KEY_SCAN_N },
    { SDL_SCANCODE_M, HOST_KEY_SCAN_M },
    { SDL_SCANCODE_COMMA, HOST_KEY_SCAN_COMMA },
    { SDL_SCANCODE_PERIOD, HOST_KEY_SCAN_PERIOD },
    { SDL_SCANCODE_SLASH, HOST_KEY_SCAN_SLASH },
    { SDL_SCANCODE_RSHIFT, HOST_KEY_SCAN_RIGHTSHIFT },
    { SDL_SCANCODE_KP_MULTIPLY, HOST_KEY_SCAN_KP_MULTIPLY },
    { SDL_SCANCODE_LALT, HOST_KEY_SCAN_LEFTALT },
    { SDL_SCANCODE_SPACE, HOST_KEY_SCAN_SPACE },
    { SDL_SCANCODE_CAPSLOCK, HOST_KEY_SCAN_CAPSLOCK },
    { SDL_SCANCODE_F1, HOST_KEY_SCAN_F1 },
    { SDL_SCANCODE_F2, HOST_KEY_SCAN_F2 },
    { SDL_SCANCODE_F3, HOST_KEY_SCAN_F3 },
    { SDL_SCANCODE_F4, HOST_KEY_SCAN_F4 },
    { SDL_SCANCODE_F5, HOST_KEY_SCAN_F5 },
    { SDL_SCANCODE_F6, HOST_KEY_SCAN_F6 },
    { SDL_SCANCODE_F7, HOST_KEY_SCAN_F7 },
    { SDL_SCANCODE_F8, HOST_KEY_SCAN_F8 },
    { SDL_SCANCODE_F9, HOST_KEY_SCAN_F9 },
    { SDL_SCANCODE_F10, HOST_KEY_SCAN_F10 },
    { SDL_SCANCODE_NUMLOCKCLEAR, HOST_KEY_SCAN_NUMLOCK },
    { SDL_SCANCODE_SCROLLLOCK, HOST_KEY_SCAN_SCROLLLOCK },
    { SDL_SCANCODE_KP_7, HOST_KEY_SCAN_KP_7 },
    { SDL_SCANCODE_KP_8, HOST_KEY_SCAN_KP_8 },
    { SDL_SCANCODE_KP_9, HOST_KEY_SCAN_KP_9 },
    { SDL_SCANCODE_KP_MINUS, HOST_KEY_SCAN_KP_MINUS },
    { SDL_SCANCODE_KP_4, HOST_KEY_SCAN_KP_4 },
    { SDL_SCANCODE_KP_5, HOST_KEY_SCAN_KP_5 },
    { SDL_SCANCODE_KP_6, HOST_KEY_SCAN_KP_6 },
    { SDL_SCANCODE_KP_PLUS, HOST_KEY_SCAN_KP_PLUS },
    { SDL_SCANCODE_KP_1, HOST_KEY_SCAN_KP_1 },
    { SDL_SCANCODE_KP_2, HOST_KEY_SCAN_KP_2 },
    { SDL_SCANCODE_KP_3, HOST_KEY_SCAN_KP_3 },
    { SDL_SCANCODE_KP_0, HOST_KEY_SCAN_KP_0 },
    { SDL_SCANCODE_KP_PERIOD, HOST_KEY_SCAN_KP_PERIOD },
    { SDL_SCANCODE_SYSREQ, HOST_KEY_SCAN_SYSREQ },
    { SDL_SCANCODE_F11, HOST_KEY_SCAN_F11 },
    { SDL_SCANCODE_F12, HOST_KEY_SCAN_F12 },
    { SDL_SCANCODE_KP_ENTER, HOST_KEY_SCAN_KP_ENTER },
    { SDL_SCANCODE_KP_DIVIDE, HOST_KEY_SCAN_KP_DIVIDE },
    { SDL_SCANCODE_RALT, HOST_KEY_SCAN_RIGHTALT },
    { SDL_SCANCODE_HOME, HOST_KEY_SCAN_HOME },
    { SDL_SCANCODE_UP, HOST_KEY_SCAN_UP },
    { SDL_SCANCODE_PAGEUP, HOST_KEY_SCAN_PAGEUP },
    { SDL_SCANCODE_LEFT, HOST_KEY_SCAN_LEFT },
    { SDL_SCANCODE_RIGHT, HOST_KEY_SCAN_RIGHT },
    { SDL_SCANCODE_END, HOST_KEY_SCAN_END },
    { SDL_SCANCODE_DOWN, HOST_KEY_SCAN_DOWN },
    { SDL_SCANCODE_PAGEDOWN, HOST_KEY_SCAN_PAGEDOWN },
    { SDL_SCANCODE_INSERT, HOST_KEY_SCAN_INSERT },
    { SDL_SCANCODE_DELETE, HOST_KEY_SCAN_DELETE },
    { SDL_SCANCODE_LGUI, HOST_KEY_SCAN_LEFTGUI },
    { SDL_SCANCODE_RGUI, HOST_KEY_SCAN_RIGHTGUI },
    { SDL_SCANCODE_APPLICATION, HOST_KEY_SCAN_APPLICATION }
};

uint8_t hostkey_sdl_translate(const SDL_KeyboardEvent* event, HOST_KEY_EVENT_t out[HOSTKEY_SDL_MAX_EVENTS])
{
    size_t i;

    if ((event == NULL) || (out == NULL)) {
        return 0;
    }

    if (event->keysym.scancode == SDL_SCANCODE_PRINTSCREEN) {
        out[0].scan = HOST_KEY_SCAN_PRINTSCREEN;
        out[0].down = (event->type == SDL_KEYDOWN) ? 1 : 0;
        return 1;
    }

    if (event->keysym.scancode == SDL_SCANCODE_PAUSE) {
        out[0].scan = HOST_KEY_SCAN_PAUSE;
        out[0].down = (event->type == SDL_KEYDOWN) ? 1 : 0;
        return 1;
    }

    for (i = 0; i < (sizeof(hostkey_sdl_map) / sizeof(hostkey_sdl_map[0])); i++) {
        if (hostkey_sdl_map[i].scancode == event->keysym.scancode) {
            out[0].scan = hostkey_sdl_map[i].host_scan;
            out[0].down = (event->type == SDL_KEYDOWN) ? 1 : 0;
            return 1;
        }
    }

    return 0;
}
